import Image from "next/image";

export default function Home() {
  return (
    <main className="flex flex-col justify-center items-center ">
      <h1 className="text-5xl mt-10">Next</h1>
      <p>Generated by create next app</p>
    </main>
  );
}
